version: '3.8'
services:
  web:
    build: ./myapp
    container_name: myapp-compose
    ports:
      - "5001:5000"
    # volumes:
    #   - ./myapp:/app  # Пример монтирования кода для разработки
    # networks:
    #   - mynet
    restart: unless-stopped

# networks:
#   mynet:
